[package]
name = "luminance-web-sys"
version = "0.1.0"
license = "BSD-3-Clause"
authors = ["Dimitri Sabadie <dimitri.sabadie@gmail.com>"]
description = "web-sys luminance platform"
keywords = ["stateless", "type-safe", "graphics", "luminance", "web-sys"]
categories = ["rendering::graphics-api"]
homepage = "https://github.com/phaazon/luminance-rs"
repository = "https://github.com/phaazon/luminance-rs"
documentation = "https://docs.rs/luminance-web-sys"
readme = "README.md"
edition = "2018"

[dependencies]
luminance = { path = "../luminance", version = "0.40" }
luminance-webgl = { path = "../luminance-webgl", version = "0.1" }
luminance-windowing = { path = "../luminance-windowing", version = "0.9" }
wasm-bindgen = "0.2.63"

[dependencies.web-sys]
version = "0.3.40"
features = [
  "Document",
  "Element",
  "HtmlCanvasElement",
  "WebGl2RenderingContext",
  "Window",
]
